### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Antony74** [gillyb/fluent-regex#1]
Congratulations, I think fluent regexs are a wonderful idea, I don't understand why it hasn't taken off more.

Anyway, I have this fork, which is

- Function rather than class-based
- Immutable
- With the addition of an exclude method for groups
- Jest rather than mocha

And which I might publish eventually, but right now I'm just curious if you have any thoughts, feedback, or advice about it?  Thanks :-)

~~https://github.com/Antony74/mmparsers/tree/main/src/fluent-regex~~

**Comment by Antony74** [comment]
[Published](https://www.npmjs.com/package/fluent-regex-fun)

**Comment by gillyb** [comment]
Hi, Sorry for just replying now.. 
Since i don't actively maintain this library, I don't regularly look at the issues here.

Anyways, I like what you did!  
I like the immutability, the addition of the exclude method and I like the fact that you used Jest (When i originally wrote this i wasn't familiar yet with jest, so I didn't use it. Have I started today, I would probably go with Jest).

Thanks for giving me credit in your updated README :)
